# Generated by Django 6.0.2 on 2026-02-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_systemsetting_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='admin_theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
