# Generated by Django 6.0.2 on 2026-02-28 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=120)),
                ('statement_month', models.DateField()),
                ('total_spend', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('minimum_due', models.IntegerField(default=0)),
                ('annual_interest_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_spends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_month', '-id'],
            },
        ),
    ]
