# Generated by Django 6.0.2 on 2026-02-28 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_creditcardspend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=120)),
                ('issuer', models.CharField(blank=True, default='', max_length=120)),
                ('emi_interest_rate', models.FloatField(default=18.0)),
                ('monthly_spend_interest_rate', models.FloatField(default=0.0)),
                ('reward_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['card_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_month', models.DateField()),
                ('entry_type', models.CharField(choices=[('emi', 'EMI'), ('monthly', 'Monthly Spend')], max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('tenure_months', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='myapp.creditcardaccount')),
            ],
            options={
                'ordering': ['-entry_month', '-id'],
            },
        ),
    ]
