# Generated by Django 6.0.2 on 2026-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_creditcardaccount_creditcardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardaccount',
            name='credit_limit',
            field=models.IntegerField(default=0),
        ),
    ]
