# Generated by Django 6.0.2 on 2026-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_creditcardaccount_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
